### ISSUE TITLE
Suggestion: a lite version for images only

### ISSUE THREAD

**Issue by flaviojcojr** [AaronFeng753/Waifu2x-Extension-GUI#145]
With each update the program gets bigger but many of the users use it only for image upscaling. Would it be possible to create a lite version just for that purpose?

**Comment by AaronFeng753** [comment]
sorry, I can't, because most of the storage is actually taken by waifu2x-caffe engine.
if you don't need to use waifu2x-caffe, you can delete the `waifu2x-caffe` folder, as long as you don't try to use it(and don't run compatibility test), program won't crash.
![image](https://user-images.githubusercontent.com/52553688/90322720-37086780-df8a-11ea-8e9a-b79b433cfecc.png)

**Comment by flaviojcojr** [comment]
Thanks Aaron!
