### ISSUE TITLE
Where is latest sources?

### ISSUE THREAD

**Issue by Neurotoxin001** [AaronFeng753/Waifu2x-Extension-GUI#342]
Hello, I can only see 3.41.01-beta sources here:
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/tree/master/SRC_v3.41.01-beta

Same version in Source code zip here:
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.87.01

Why did you not upload 3.87.01 sources?

**Comment by AaronFeng753** [comment]
Because I can't keep updating this nearly every week if no one is gonna pay me anything and it takes me more than one year to found out most people don't wanna pay for open source projects.

I am sorry but I also need money to buy food and survive, or I will starve to death, lol

This issue will be deleted later because it's not really a bug report or feature request.
