### ISSUE TITLE
Amd driver 22Q2 have the same problem as 22.5.2

### ISSUE THREAD

**Issue by Panday-Ichihara** [AaronFeng753/Waifu2x-Extension-GUI#400]
Maybe all the new drivers will come with this issue. 
Not compatible.

**Comment by AaronFeng753** [comment]
I just checked, the latest optional driver is still 22.5.2

https://www.amd.com/en/support/graphics/amd-radeon-rx-6000-series/amd-radeon-rx-6700-series/amd-radeon-rx-6750-xt

Idk, I just gonna edit the title of that issue, the latest recommended driver is still not changed so I still believe this is a beta driver issue

**Comment by AaronFeng753** [comment]
Since my main computer is using rtx 3060 and Nvidia also released new driver only like 3 days ago (516.40), so I installed the new driver, run the compatibility test, and still no problem occurred. 

So I still believe it's most likely AMD broke their driver and I will wait for the next recommended driver update

**Comment by Panday-Ichihara** [comment]
yeah, i hope they solve it, the pro line is just a name you can use it in rx500,400. the pro drivers is just a more tested and stable driver.

**Comment by AaronFeng753** [comment]
Yeah! AMD fixed their latest optional driver! (22.6.1)
🎉🎉🎉🎉
I just tested it on my Rx 550 and everything works just fine
