### ISSUE TITLE
Real-ESRGAN Speed Question - 3090 slower then 2080.

### ISSUE THREAD

**Issue by L0garithmic** [AaronFeng753/Waifu2x-Extension-GUI#436]
I am running the most current Waifu2x-GUI on two computers at the moment.

PC1
i7-12700KF
16GB DDR4
Win 10 21H2 19044.2130
RTX 2080
6GB VRam
Waifu2x-GUI v3.95.23

PC2
Ryzen 9 5900x
32GB DDR4
Win 10 21H2 19044.2130
RTX 3090
6GB VRam
Waifu2x-GUI v3.95.23 Premium

I am upscaling the same files. The 2080 build estimates 29 minutes, the 3090 build estimates 33 minutes. 
The 3090 is 40-50% faster then the 2080. Is there a reason this is happening

Both have the same settings. The 3090 build is premium. Is there a reason the 3090 is slower?

**Comment by AaronFeng753** [comment]
1. I can't test this because I couldn't afford 2080+3090 just for testing this
2. Please check your settings again, like block size and number of threads of the engine, and your video settings if you were processing videos
3. The Premium version could cause the time difference if you enabled preminum only settings like these:
Please make sure you disabled them in both the 2080 and 3090 build
![2022-11-02_11-58-55](https://user-images.githubusercontent.com/52553688/199392593-077b4393-1cc1-497b-b942-582c7d8b34be.jpg)
