### ISSUE TITLE
RTX graphics card and Intel graphics card

### ISSUE THREAD

**Issue by Platorius** [AaronFeng753/Waifu2x-Extension-GUI#442]
Do RTX graphics card benefit in this software ? So is an RTX card with same compute power as an GTX card better because of RTX?
And are Intel graphics cards (not iGPU) supportet? Because I red they do a good job on things like Upscaling.

Sorry, dont know, where I can find such information.

**Comment by AaronFeng753** [comment]
> Do RTX graphics card benefit in this software ?  So is an RTX card with same compute power as an GTX card better because of RTX?

NO

> And are Intel graphics cards (not iGPU) supported?

If they support vulkan, than yes they are supported. I don't have those now intel GPU so I am also not exactly sure about their compatibility. But they should be compatible since some iGPUs are already compatible.

### This issue will be closed and locked because it's not a bug report or enhancement suggestions.
