### ISSUE TITLE
[Feature request] Skip processing of black frames

### ISSUE THREAD

**Issue by VladWinner** [AaronFeng753/Waifu2x-Extension-GUI#456]
I noticed that it takes too much time to process frames entirely filled with one color, which can be reduced if Waifu2x-Extension-GUI applies the simplest image scaling algorithm to pre-identified frames and skips further enhancement actions for them.

**Comment by AaronFeng753** [comment]
Similar feature already exists 

Video settings ➡️ Frame analysis ➡️ Speed boost & Pre-processing boost 

Duplicated frames will be skipped when they are enabled, since most video won't just put lots of black frames between every normal frames, I don't think a feature that only identify black frames is necessary 

So this issue will be closed and locked
