### ISSUE TITLE
[BUG] Program closes after I start upscaling

### ISSUE THREAD

**Issue by Andrey24SP** [AaronFeng753/Waifu2x-Extension-GUI#545]
I start the program as usual, put in the videos, select the engine and start it.
After a few seconds, it closes the program and can only be found in task manager, using 0% of everything.
If I try to get back in the program, it won't work, only if I reinstall and restart the pc.
I don't know what do to anymore, tried both beta and stable versions, same problem.
Any fixes?

**Comment by AaronFeng753** [comment]
I just received a similar report from another user few days ago, turns out that it's caused by Kaspersky

And the reason is some lazy antivirus software just label small software project like this as virus without checking, so it probably just killed and deleted my software without any warning. Personally I am using eset, never had these issues.

So if you are using similar antivirus software, just add my software to its white list or disable it and try again

**Comment by Andrey24SP** [comment]
I only use windows defender, haven't installed malwarebytes again, but I'll whitelist it there and hope everything is good.
Thanks for the help!
