### ISSUE TITLE
It would be nice to have a pause button

### ISSUE THREAD

**Issue by 4-testing** [AaronFeng753/Waifu2x-Extension-GUI#59]
It would be nice to have a pause button. Right now if one needs to use the computer  while Waifu2x-Extension-GUI is running, the only choice is stop, which deletes everything done so far.

**Comment by AaronFeng753** [comment]
For the video pause problem, my current solution is:
During the processing of the video, the cache is no longer deleted when paused or made an error, and at the beginning again, if the step of zooming in has been reached before, the software will automatically read the previous temporary storage and continue to zoom in. The temporary buffer will only be deleted after the zoom is successful. Save.
Of course, you can also check the settings so that the software will never delete your video temporary.
Now the latest version of the source code already supports the features I said above, please wait for updates.
`Translated by Google , because I'm lazy`

**Comment by AaronFeng753** [comment]
new update is available now: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest
